### ISSUE TITLE
How to prepare the scene viewer 

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#13]
Hi Raluca, 
I would like to know how to prepare the scene on arcgis.

I have created a scene and it runs, but the buttons: Color by construction year, Color by height, and Color by usage do not work, when I click the any button the objects (buildings) disapear.

Could you help me?
Fernando.

**Comment by RalucaNicola** [comment]
Hi Fernando, there are many reasons why this might not work. 

Do you get any errors in the console? 

You should update this file with the values in your dataset: https://github.com/RalucaNicola/JSAPI_demos/blob/master/sanfrancisco-buildings/app/config.js.

**Comment by flimasuoc** [comment]
Sorry, I did not tell you witch app. The app is San Francisco.
I've updated the config.js file, however  the buildings disapear whe I click on button "Colors by Year" or any other.

Could you check my base scene, it is [here](https://arcg.is/qyTLK).
Wheen I change the renderers, some like this
`                    symbol: {
                        type: "polygon-3d",
                        symbolLayers: [{
                            type: "extrude",
                            size: 40,
                            material: {
                                color: element.color,
                                colorMixMode: "replace"
                            },
                        }]
                    }
`
The app shows the polygons but the filters do not work still.
Fernando.

**Comment by ghost** [comment]
Sorry, I did not tell you witch app. The app is San Francisco.
I've updated the config.js file, however the buildings disappear when I click on button "Colors by Year" or any other.

Could you check my base scene, it is [here](https://arcg.is/qyTLK).
Wheen I change the renderers, some like this
`symbol: { type: "polygon-3d", symbolLayers: [{ type: "extrude", size: 40, material: { color: element.color, colorMixMode: "replace" }, }] }
`
The app shows the polygons but the filters do not work still.
Fernando.

**Comment by RalucaNicola** [comment]
Hard to say, I think the problem is somewhere in the app. Is it a private repo, could you maybe share it with me somehow so I can have a look? you could add me as a collaborator.

**Comment by ghost** [comment]
I think that the scene is the problem. 
I only change the initial parameters (url, layer, year, height, and usage), then the app read the scene but the objects can't work fine. 

Could I share you the scene in ArcGIS online?

Fernando.

**Comment by RalucaNicola** [comment]
My scene is in the config file: https://github.com/RalucaNicola/JSAPI_demos/blob/master/sanfrancisco-buildings/app/config.js -> https://jsapi.maps.arcgis.com/home/item.html?id=2e38f798f3124f2dae84217839cc43dc

Did you also change the values that are used for the renderers? For example the usage values are different in your data: https://github.com/RalucaNicola/JSAPI_demos/blob/master/sanfrancisco-buildings/app/config.js#L54

Do you use `begin_year` in the yearField? That looks like it should work. Do you get any errors in the console?

**Comment by RalucaNicola** [comment]
I'd be happy to debug your app, but without the code it's a bit hard to figure out where the problem comes from...
