### ISSUE TITLE
Update "About" section to reflect the product name change

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#17]
## Description

_ArcGIS API for JavaScript_ got rebranded as _ArcGIS Maps SDK for JavaScript_. This name change should be reflected in the _About_ section of this repository.

![image](https://user-images.githubusercontent.com/63106648/216551121-b4870366-21ac-4ae8-a40f-ac0bb97ba178.png)

The about section is set in the repository's settings. I can't access there and/or make a PR to change the name.

**Comment by RalucaNicola** [comment]
Done!
