### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by d-wasserman** [RalucaNicola/JSAPI_demos#2]
Hi Raluca, 

I think all the demos you have compiled here are incredible. The sketch the city demo in particular is one I am very interested in. However, there is no [licence](https://choosealicense.com/) attached to it.

Is it possible to add a [license](https://choosealicense.com/) so the terms of use are clear? 

Thanks, 

David W.

**Comment by RalucaNicola** [comment]
Hi David,

thanks for the notice! I added an Apache License 2.0 to the repo. 
Happy that you like the demos and have fun tweaking the code and creating your own visualizations!

**Comment by d-wasserman** [comment]
Thank you! I am looking forward to using it with some TOD Rules I am working on and some AV projects. =)
You can close this issue at your leisure.

**Comment by RalucaNicola** [comment]
Nice, would be cool to see what you worked on once you have smth up and running, I'm always curious to see what others visualize in 3D :-)

**Comment by d-wasserman** [comment]
> Nice, would be cool to see what you worked on once you have smth up and running, I'm always curious to see what others visualize in 3D :-)

I will be sure to report back! Thank you!
