### ISSUE TITLE
Low poly world demo broken since 4.24

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#21]
## Description

Low-poly world demo is broken since API version 4.24. Found while updating apps to 4.26 and reverted back to 4.23 for the sample to work in the mean time.

The sample started to break with 4.24 because `https://js.arcgis.com/4.24/esri/tasks/QueryTask.js` can't be found anymore. This is because tasks in `esri/tasks` have been [deprecated](https://developers.arcgis.com/javascript/latest/4.20/#rest-modules) with `4.20` and support was removed in `4.24`, see [release notes](https://developers.arcgis.com/javascript/latest/4.24/#breaking-changes). 

Tasks have been moved to `esri/rest` with a similar interface. It should be straight forward to update.

**Comment by RalucaNicola** [comment]
Done!
