### ISSUE TITLE
SketchCities: WebScene for Washington D.C. requires login

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#23]
## Description

When loading Washington D.C. in the SketchCities example, the website prompts for username/password indicating that the webscene is not publicly available anymore.

https://ralucanicola.github.io/JSAPI_demos/sketch-the-city/?id=3c647dba420a4f3da9091ae83772e78e

![image](https://user-images.githubusercontent.com/63106648/216589398-a4eab7f8-09ce-4886-98e2-5cc90a6e31a7.png)

**Comment by RalucaNicola** [comment]
Strange, I tried this in an incognito window and it seems to load the scene just fine... @romanCattaneo can you try again and let me know if you run into issues?

**Comment by ghost** [comment]
Strange indeed. I can confirm that all data loads as expected now. Closing the issue as "could not reproduce".
