### ISSUE TITLE
SketchCities: loading stays even if scene is seemingly done loading

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#24]
## Description

The very prominent loading indicator in the middle of the screen stays even if the scene is seemingly done with loading.

![image](https://user-images.githubusercontent.com/63106648/216589774-7e1353b3-7a5a-4d48-8518-507371fcc2f9.png)

**Comment by RalucaNicola** [comment]
Hah... seems like I should wait for the view to be ready, otherwise `view.goTo` throws an abort error... strange that it worked before... maybe we're even slower with creating the view these days...

Added a fix to wait for the view.
