### ISSUE TITLE
Cassini globe throws tile fetching errors when zooming in

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#28]
## Description

Resolution of the cassini globe is limited. When zooming in "too much", we start to see tile loading errors on the console. Consider adding a zoom limit and/or ignoring the errors. Note: Nothing is fundamentally broken here. If you zoom in "too much", you'll just get blurry resolution as expected.

**Comment by RalucaNicola** [comment]
Done! It makes no sense to zoom in that far anyway.
