### ISSUE TITLE
urban sketch: data unavailable

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#29]
## Description

It looks like data for the urban sketch sample is not available anymore. Console errors indicate this by a 404 error from the building scene server.

![image](https://user-images.githubusercontent.com/63106648/216593453-ee2c6257-51a0-4e44-ace0-b2a043d63796.png)

**Comment by RalucaNicola** [comment]
I had to remove it, Devin removed the data. The demo is not that important to ask him again about the data, so I decided to just remove the app...
