### ISSUE TITLE
Sketch The City Style Suggestion - Water Color

### ISSUE THREAD

**Issue by d-wasserman** [RalucaNicola/JSAPI_demos#3]
Hi Raluca, 

I have a live copy of the sketch the city app on my own fork. After experimenting a bit with the sketch/styling, I got an idea for a "water color" style. I was thinking it would be great is the native color of the SPK showed through the style. I got this to happen by commenting out the material settings, and boosting the extension length. I was wondering if you had any ideas beyond this to get this to be more "water color" style. I know  I have a project or two that could use something like this. 

David

**Comment by RalucaNicola** [comment]
Hi David, 

late reply, devsummit took over everything else...
yeah, this is one of the things that I'd love to see, but I don't really have the skills to create a watercolor rendering of a scene. I tried a small workaround once by adding the watercolor basemap from Stamen:

![image 3](https://user-images.githubusercontent.com/8091967/54010456-25a11600-416f-11e9-98d0-978d09b57eb1.png)

Your suggestion sounds interesting though...so would you create a watercolor like texture and apply it to the buildings? with `colorMixMode` you can set how the color interacts with the texture...

**Comment by d-wasserman** [comment]
That is ultimately what I ended up with (or set up). I will send an example tomorrow, but I essentially set the color mode to "multiply" rather than replace. I will send a block quote of changes. Right now it looks like color pencil, but maybe a more explicit texture might work too. I think ideally you could apply a watercolor dirt map in the render of the buildings, and then use the actual color (of the face/material) to get the color. 

The stamen water color base map is genius. I was not sure you could get the elevation to work with that, but that might be the approach to take here too.

**Comment by RalucaNicola** [comment]
oh, that sounds cool, I'd be curious to see that. How did you apply the texture?

it's not really genius, it's more of a workaround...

**Comment by d-wasserman** [comment]
Sorry for my delay. 

I did not apply a texture yet (it was an "ideal" idea), that might be possible with a CGA rule perhaps? Regardless, this is what I managed by changing the color settings. 
![2019-03-12 09_39_50-App Screenshot](https://user-images.githubusercontent.com/8280073/54218764-679dc500-44ab-11e9-971a-c281a8979408.png)




It is a workaround that complements the idea and I appreciate regardless.

**Comment by RalucaNicola** [comment]
oh I like it! That looks nice :) yes, you could definitely set some textures in City Engine that would look like watercolor paper and then you could apply colors...it will not be a water color renderer, but I guess it would look nice. I'm currently working on a map that tries to mimic an old map. I will probably try there some textures to see what effects I can get...

**Comment by d-wasserman** [comment]
It is not exactly water color, but I would like to get it closer with some edits. It might be that edge rendering would need a "blur" parameter to get closer...

I look forward to see what you can do then.

**Comment by RalucaNicola** [comment]
will go ahead and close this ticket @d-wasserman. Didn't get to experiment much with this and I don't think I'll have time in the near future. But thanks a lot for the cool idea!
