### ISSUE TITLE
Missing basemap in multiple samples (blocked by CORS policy)

### ISSUE THREAD

**Issue by ghost** [RalucaNicola/JSAPI_demos#30]
## Description

It seems like access to the basemap in some example is blocked by CORS policies.

![image](https://user-images.githubusercontent.com/63106648/216594188-7c24b9b4-3eec-4837-ac8a-a47a599d8ccd.png)

Affected are - as far as I could see -

- Boston urban development example
- San Francisco public transport example
- Christmas map

**Comment by RalucaNicola** [comment]
So strange, the vector tile basemap disappeared... both apps used that. There used to be a chromium style, maybe Esri removed it 🤷‍♀️ 
I just added a simple gray basemap. And I removed the Christmas app, I've been wanting to remove it for a while now.
