### ISSUE TITLE
running example

### ISSUE THREAD

**Issue by FrancisBases** [RalucaNicola/JSAPI_demos#7]
Hello Raluca and congratulations for wonderful works.

So was trying to reproduce locally https://ralucanicola.github.io/JSAPI_demos/sanfrancisco-buildings/ with your repository https://github.com/RalucaNicola/JSAPI_demos/tree/master/sanfrancisco-buildings.

After downloading the zip and running locally the html. Although all i get is the following:
![image](https://user-images.githubusercontent.com/24868420/83825611-b0a1f080-a6d1-11ea-92ed-6d92f610a285.png)

If you can give some hints on how to fix this would be appreciated in advance.

**Comment by RalucaNicola** [comment]
I believe you would need a webserver to make it run. Do you have one?
Can you check the console for errors?

**Comment by FrancisBases** [comment]
Ok thank you very much will use own scene and it should work cheers.

**Comment by RalucaNicola** [comment]
Closing, write to me on slack if you still run into issues.

**Comment by FrancisBase** [comment]
Hello Raluca i have sent you a report of the application results in slack because i have made some advances but is not yet fully working. If it is possible any help is appreciated so thanks in advance.
